<a href="https://colab.research.google.com/github/saulor5/JuegoSecreto/blob/main/Codificador_y_decodificador_de_mensajes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [593]:
import numpy as np
#Declaramos a nuestra matriz llave
matriz_llave = np.array ([[2, 4, 3], [0, 1, -1], [3, 5, 7]])
print (matriz_llave)

[[ 2  4  3]
 [ 0  1 -1]
 [ 3  5  7]]


In [594]:
#Ingresamos la matriz de nuestro mensaje
B = np.array ([[8, 26, 14, 1, 15, 5, 1, 4, 8],
               [15, 13, 1, 26, 26, 26, 14, 9, 15],
               [25, 1, 14, 14, 19, 8, 26, 3, 26]])
print (B)

[[ 8 26 14  1 15  5  1  4  8]
 [15 13  1 26 26 26 14  9 15]
 [25  1 14 14 19  8 26  3 26]]


In [595]:
#Multiplicamos la matriz llave por la matriz de nuestro mensaje
C = np.dot(matriz_llave,B)
print (C)

[[151 107  74 148 191 138 136  53 154]
 [-10  12 -13  12   7  18 -12   6 -11]
 [274 150 145 231 308 201 255  78 281]]


In [596]:
#Aplicamos modulo 29
mesaje_cifrado = C % 29
print (mesaje_cifrado)

[[ 6 20 16  3 17 22 20 24  9]
 [19 12 16 12  7 18 17  6 18]
 [13  5  0 28 18 27 23 20 20]]


In [597]:
def inverso_modular(a, m):
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    return None #Si no existe inverso
  #Resultado de inverso modular
print (inverso_modular(3, 29))

10


In [598]:
def desencriptar(matriz_llave, mensaje_cifrado):
    #Obtenemos la determinante de la matriz llave
    det_A = np.linalg.det((matriz_llave))
    #Redondeamos el valor del determinante
    det_A_b = round(det_A)
    #Obtenemos la matriz inversa del determinante de la matriz llave
    inv_det_A = inverso_modular(int(det_A_b), 29)
    #Obtenemos la inversa de la matriz llave para poder calcular
    #la matriz adjunta de la matriz llave
    inv_matriz_llave = np.linalg.inv(matriz_llave)
    #Obtenemos la matriz adjunta de la matriz llave
    adj_A = np.dot(det_A, inv_matriz_llave)
    #Obtenemos la matriz inversa
    matriz_inversa = (inv_det_A * adj_A) % 29
    #Obtenemos el mensaje original
    mensaje_original = np.mod (np.dot(matriz_inversa, mensaje_cifrado),29)


    return mensaje_original, det_A, inv_det_A


mensaje_original, det_A, inv_det_A = desencriptar(matriz_llave, mesaje_cifrado)

print ("Determinante de A", det_A)
print ("Matriz inversa del determinante de la matriz", inv_det_A)
print (mensaje_original)

Determinante de A 2.999999999999998
Matriz inversa del determinante de la matriz 10
[[ 8. 26. 14.  1. 15.  5.  1.  4.  8.]
 [15. 13.  1. 26. 26. 26. 14.  9. 15.]
 [25.  1. 14. 14. 19.  8. 26.  3. 26.]]
